---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: block-devs
spec:
  selector:
    matchLabels:
      app: block-devs
  replicas: 0
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: block-devs
    spec:
      terminationGracePeriodSeconds: 2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - block-devs
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - block-devs
                topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
        - name: centos
          image: centos:7
          command: ["/bin/bash", "-c"]
          args: ["sleep infinity"]
          volumeDevices:
            - name: block
              devicePath: /dev/my-block
  volumeClaimTemplates:
    - metadata:
        name: block
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName: "my-storage-class"
        volumeMode: Block
        resources:
          requests:
            storage: 1Ti
