---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: block-devs
spec:
  selector:
    matchLabels:
      app: block-devs # has to match .spec.template.metadata.labels
  #serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: block-devs # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            #labelSelector:
            #  matchExpressions:
            #  - key: kubernetes.io/hostname
            #    operator: In
            #    values:
            #    - S2
            topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - name: centos
        image: centos:7
        command: ["/bin/bash", "-c"]
        args: ["sleep infinity"]
        volumeDevices:
        - name: block
          devicePath: /dev/my-block
  volumeClaimTemplates:
  - metadata:
      name: block
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: "my-storage-class"
      volumeMode: Block
      resources:
        requests:
          storage: 1Ti
