---

apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14
    allowUnsupported: false
  # Even w/ PVs, this must be set or mons fail to start due to permission
  # problems
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: false
  mon:
    count: 3
    allowMultiplePerNode: false
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  annotations:
  resources:
  storage:
    storageClassDeviceSets:
      - name: set1
        count: 3
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 25Gi
              storageClassName: local-block
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    topologyAware: true
