---

apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: openshift-storage
spec:
  # hostNetwork: true
  manageNodes: false
  monPVCTemplate:
    spec:
      storageClassName: gp2
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  storageDeviceSets:
  - name: mydeviceset
    count: 3
    dataPVCTemplate:
      spec:
        storageClassName: gp2
        accessModes:
          - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1Ti
    placement: {}
    portable: true
    resources: {}
