---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-subscription
  namespace: openshift-storage
spec:
  channel: stable-4.3
  name: ocs-operator
  source: ocs-catalogsource
  sourceNamespace: openshift-marketplace
